framework:
    asset_mapper:
        paths:
            - assets/
            # Syntaxe simplifi√©e : on donne le chemin physique
            - vendor/symfony/stimulus-bundle/assets/dist/

        missing_import_mode: strict
