framework:
    router:
<<<<<<< HEAD
        utf8: true

        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        #default_uri: http://localhost
=======
        # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
        # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
        default_uri: '%env(DEFAULT_URI)%'
>>>>>>> 36a4293e1a9bb7a7545a4bbefbe00ef463bcbc97

when@prod:
    framework:
        router:
            strict_requirements: null
