framework:
    validation:
<<<<<<< HEAD
        email_validation_mode: html5

=======
>>>>>>> 36a4293e1a9bb7a7545a4bbefbe00ef463bcbc97
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
