# config/services.yaml
parameters:
    photo_directory: '%kernel.project_dir%/public/uploads/photos'


    photos_directory: '../public/photo'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude: [ '../src/DependencyInjection/', '../src/Kernel.php' ]
